* Introduction
This is a library for reading =.kra= files.

** TODO Features
*** TODO Reading
+ [-] Parsing metadata
  - [X] Supports these layer types:
    1. PaintLayer
    2. GroupLayer
    3. FilterMask
    4. SelectionMask
  - [ ] Does not support these layer types yet
    1. FileLayer
    2. FilterLayer
    3. FillLayer
    4. CloneLayer
    5. VectorLayer
    6. TransparencyMask
    7. TransformMask
    8. ColorizeMask
  - [ ] It does not register what layer was selected at the moment of saving (attribute ~selected="true"~).
+ [ ] Extracting images
*** Writing
Currently, there are no plans to support editing parsed data and writing =.kra= files outside of Krita.
This may change in the future.
*** Rendering
Rendering is best be left to a different crate.
** TODO Tasks
*** NEXT Finish preparing other layers
As noted [[*Reading][here]]
*** NEXT Publishing
+ [ ] Docs
+ [ ] Tests
+ [ ] Examples
*** CURRENT Refactoring
+ [ ] Consider moving (or similar action) license and readme to =kra=, in some way
  - This is because the crate itself needs to have the license, at the source root, not at the repo's root.
  - Do note that =kra-macro= is to be published too, and it probably should be under the same license terms too.
    Copy or hardlink it to there too?
* License
The library is licensed under GPL 3.0 because some of its code is or will be adapted from Krita's.
