* Introduction
This is a library for reading =.kra= files.

** TODO Features
*** TODO Reading
+ [-] Parsing metadata
  - [X] Supports these layer types:
    1. PaintLayer
    2. GroupLayer
    3. FilterMask
    4. SelectionMask
  - [ ] Does not support these layer types (but adding support should be easy):
    1. FileLayer
    2. FilterLayer
    3. FillLayer
    4. CloneLayer
    5. VectorLayer
    6. TransparencyMask
    7. TransformMask
    8. ColorizeMask
  - [ ] It does not register what layer was selected at the moment of saving (attribute ~selected="true"~).
+ [ ] Extracting images
*** Writing
Currently, there are no plans to support editing parsed data and writing =.kra= files outside of Krita.
This may change in the future.
*** Rendering
Rendering is best be left to a different crate.
** TODO Tasks
*** CURRENT Publishing
+ [ ] Docs
+ [ ] Tests
+ [ ] Examples
*** Refactoring
+ [ ] Generate parsing code instead of writing it by hand.
* License
The library is licensed under GPL 3.0 because some of its code is or will be adapted from Krita's.
