//! Dummy types that are used in place of types from `kra` when feature `data`
//! is not used.

use std::{
    fmt::{self, Display},
    str::FromStr,
};

use crate::error::{UnknownColorspace, UnknownCompositeOp};

// TODO: fill out with more variants
/// Colorspace identifier.
#[derive(Debug, PartialEq, Eq, Clone, Copy, Hash)]
#[non_exhaustive]
#[derive(Default)]
pub enum Colorspace {
    /// Default RGBA colorspace.
    #[default]
    RGBA,
}

impl TryFrom<&str> for Colorspace {
    type Error = UnknownColorspace;

    fn try_from(value: &str) -> Result<Self, Self::Error> {
        match value {
            "RGBA" => Ok(Colorspace::RGBA),
            // NOTE: these come from ConvertColorSpaceNames function from kis_kra_loader.cpp
            // and are intended for old colorspacenames.
            // "Grayscale + Alpha" => Ok(Colorspace::),
            // "RgbAF32" => Ok(Colorspace::),
            // "RgbbAF16" => Ok(Colorspace::),
            // "CMYKA16" => Ok(Colorspace::),
            // "GrayF32" => Ok(Colorspace::),
            // "GRAYA16" => Ok(Colorspace::),
            // "XyzAF16" => Ok(Colorspace::),
            // "XyzAF32" => Ok(Colorspace::),
            // "YCbCrA" => Ok(Colorspace::),
            // "YCbCrAU16" => Ok(Colorspace::),
            other => Err(UnknownColorspace(other.to_owned())),
        }
    }
}

impl Display for Colorspace {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Colorspace::RGBA => write!(f, "RGBA"),
        }
    }
}

/// Composition operator.
#[allow(missing_docs)]
#[derive(Debug, PartialEq, Eq, Clone, Copy, Hash)]
#[non_exhaustive]
pub enum CompositeOp {
    Normal,
    Erase,
    In,
    Out,
    AlphaDarken,
    DestinationIn,
    DestinationAtop,
    Xor,
    Or,
    And,
    Nand,
    Nor,
    Xnor,
    Implication,
    NotImplication,
    Converse,
    NotConverse,
    Plus,
    Minus,
    Add,
    Subtract,
    InverseSubtract,
    Diff,
    Multiply,
    Divide,
    ArcTangent,
    GeometricMean,
    AdditiveSubtractive,
    Negation,
    Modulo,
    ModuloContinuous,
    DivisiveModulo,
    DivisiveModuloContinuous,
    ModuloShift,
    ModuloShiftContinuous,
    Equivalence,
    Allanon,
    Parallel,
    GrainMerge,
    GrainExtract,
    Exclusion,
    HardMix,
    HardMixPhotoshop,
    HardMixSofterPhotoshop,
    Overlay,
    Behind,
    Greater,
    HardOverlay,
    Interpolation,
    Interpolation2X,
    PenumbraA,
    PenumbraB,
    PenumbraC,
    PenumbraD,
    Darken,
    Burn,
    LinearBurn,
    GammaDark,
    ShadeIfsIllusions,
    FogDarkenIfsIllusions,
    EasyBurn,
    Lighten,
    Dodge,
    LinearDodge,
    Screen,
    HardLight,
    SoftLightIfsIllusions,
    SoftLightPegtopDelphi,
    SoftLight,
    SoftLightSvg,
    GammaLight,
    GammaIllumination,
    VividLight,
    FlatLight,
    LinearLight,
    PinLight,
    PnormA,
    PnormB,
    SuperLight,
    TintIfsIllusions,
    FogLightenIfsIllusions,
    EasyDodge,
    LuminositySai,
    Hue,
    Color,
    Saturation,
    IncSaturation,
    DecSaturation,
    Luminize,
    IncLuminosity,
    DecLuminosity,
    HueHsv,
    ColorHsv,
    SaturationHsv,
    IncSaturationHsv,
    DecSaturationHsv,
    Value,
    IncValue,
    DecValue,
    HueHsl,
    ColorHsl,
    SaturationHsl,
    IncSaturationHsl,
    DecSaturationHsl,
    Lightness,
    IncLightness,
    DecLightness,
    HueHsi,
    ColorHsi,
    SaturationHsi,
    IncSaturationHsi,
    DecSaturationHsi,
    Intensity,
    IncIntensity,
    DecIntensity,
    Copy,
    CopyRed,
    CopyGreen,
    CopyBlue,
    TangentNormalmap,
    Colorize,
    Bumpmap,
    CombineNormal,
    Clear,
    Dissolve,
    Displace,
    Nocomposition,
    PassThrough, //from source: not implemented anywhere yet
    DarkerColor,
    LighterColor,
    Undefined,
    Reflect,
    Glow,
    Freeze,
    Heat,
    GlowHeat,
    HeatGlow,
    ReflectFreeze,
    FreezeReflect,
    HeatGlowFreezeReflectHybrid,
    LambertLighting,
    LambertLightingGamma22,
}

impl FromStr for CompositeOp {
    type Err = UnknownCompositeOp;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        Ok(match s {
            "normal" => CompositeOp::Normal,
            "erase" => CompositeOp::Erase,
            "in" => CompositeOp::In,
            "out" => CompositeOp::Out,
            "alphadarken" => CompositeOp::AlphaDarken,
            "destination-in" => CompositeOp::DestinationIn,
            "destination-atop" => CompositeOp::DestinationAtop,
            "xor" => CompositeOp::Xor,
            "or" => CompositeOp::Or,
            "and" => CompositeOp::And,
            "nand" => CompositeOp::Nand,
            "nor" => CompositeOp::Nor,
            "xnor" => CompositeOp::Xnor,
            "implication" => CompositeOp::Implication,
            "not_implication" => CompositeOp::NotImplication,
            "converse" => CompositeOp::Converse,
            "not_converse" => CompositeOp::NotConverse,
            "plus" => CompositeOp::Plus,
            "minus" => CompositeOp::Minus,
            "add" => CompositeOp::Add,
            "subtract" => CompositeOp::Subtract,
            "inverse_subtract" => CompositeOp::InverseSubtract,
            "diff" => CompositeOp::Diff,
            "multiply" => CompositeOp::Multiply,
            "divide" => CompositeOp::Divide,
            "arc_tangent" => CompositeOp::ArcTangent,
            "geometric_mean" => CompositeOp::GeometricMean,
            "additive_subtractive" => CompositeOp::AdditiveSubtractive,
            "negation" => CompositeOp::Negation,
            "modulo" => CompositeOp::Modulo,
            "modulo_continuous" => CompositeOp::ModuloContinuous,
            "divisive_modulo" => CompositeOp::DivisiveModulo,
            "divisive_modulo_continuous" => CompositeOp::DivisiveModuloContinuous,
            "modulo_shift" => CompositeOp::ModuloShift,
            "modulo_shift_continuous" => CompositeOp::ModuloShiftContinuous,
            "equivalence" => CompositeOp::Equivalence,
            "allanon" => CompositeOp::Allanon,
            "parallel" => CompositeOp::Parallel,
            "grain_merge" => CompositeOp::GrainMerge,
            "grain_extract" => CompositeOp::GrainExtract,
            "exclusion" => CompositeOp::Exclusion,
            "hard mix" => CompositeOp::HardMix,
            "hard_mix_photoshop" => CompositeOp::HardMixPhotoshop,
            "hard_mix_softer_photoshop" => CompositeOp::HardMixSofterPhotoshop,
            "overlay" => CompositeOp::Overlay,
            "behind" => CompositeOp::Behind,
            "greater" => CompositeOp::Greater,
            "hard overlay" => CompositeOp::HardOverlay,
            "interpolation" => CompositeOp::Interpolation,
            "interpolation 2x" => CompositeOp::Interpolation2X,
            "penumbra a" => CompositeOp::PenumbraA,
            "penumbra b" => CompositeOp::PenumbraB,
            "penumbra c" => CompositeOp::PenumbraC,
            "penumbra d" => CompositeOp::PenumbraD,
            "darken" => CompositeOp::Darken,
            "burn" => CompositeOp::Burn,
            "linear_burn" => CompositeOp::LinearBurn,
            "gamma_dark" => CompositeOp::GammaDark,
            "shade_ifs_illusions" => CompositeOp::ShadeIfsIllusions,
            "fog_darken_ifs_illusions" => CompositeOp::FogDarkenIfsIllusions,
            "easy burn" => CompositeOp::EasyBurn,
            "lighten" => CompositeOp::Lighten,
            "dodge" => CompositeOp::Dodge,
            "linear_dodge" => CompositeOp::LinearDodge,
            "screen" => CompositeOp::Screen,
            "hard_light" => CompositeOp::HardLight,
            "soft_light_ifs_illusions" => CompositeOp::SoftLightIfsIllusions,
            "soft_light_pegtop_delphi" => CompositeOp::SoftLightPegtopDelphi,
            "soft_light" => CompositeOp::SoftLight,
            "soft_light_svg" => CompositeOp::SoftLightSvg,
            "gamma_light" => CompositeOp::GammaLight,
            "gamma_illumination" => CompositeOp::GammaIllumination,
            "vivid_light" => CompositeOp::VividLight,
            "flat_light" => CompositeOp::FlatLight,
            "linear light" => CompositeOp::LinearLight,
            "pin_light" => CompositeOp::PinLight,
            "pnorm_a" => CompositeOp::PnormA,
            "pnorm_b" => CompositeOp::PnormB,
            "super_light" => CompositeOp::SuperLight,
            "tint_ifs_illusions" => CompositeOp::TintIfsIllusions,
            "fog_lighten_ifs_illusions" => CompositeOp::FogLightenIfsIllusions,
            "easy dodge" => CompositeOp::EasyDodge,
            "luminosity_sai" => CompositeOp::LuminositySai,
            "hue" => CompositeOp::Hue,
            "color" => CompositeOp::Color,
            "saturation" => CompositeOp::Saturation,
            "inc_saturation" => CompositeOp::IncSaturation,
            "dec_saturation" => CompositeOp::DecSaturation,
            "luminize" => CompositeOp::Luminize,
            "inc_luminosity" => CompositeOp::IncLuminosity,
            "dec_luminosity" => CompositeOp::DecLuminosity,
            "hue_hsv" => CompositeOp::HueHsv,
            "color_hsv" => CompositeOp::ColorHsv,
            "saturation_hsv" => CompositeOp::SaturationHsv,
            "inc_saturation_hsv" => CompositeOp::IncSaturationHsv,
            "dec_saturation_hsv" => CompositeOp::DecSaturationHsv,
            "value" => CompositeOp::Value,
            "inc_value" => CompositeOp::IncValue,
            "dec_value" => CompositeOp::DecValue,
            "hue_hsl" => CompositeOp::HueHsl,
            "color_hsl" => CompositeOp::ColorHsl,
            "saturation_hsl" => CompositeOp::SaturationHsl,
            "inc_saturation_hsl" => CompositeOp::IncSaturationHsl,
            "dec_saturation_hsl" => CompositeOp::DecSaturationHsl,
            "lightness" => CompositeOp::Lightness,
            "inc_lightness" => CompositeOp::IncLightness,
            "dec_lightness" => CompositeOp::DecLightness,
            "hue_hsi" => CompositeOp::HueHsi,
            "color_hsi" => CompositeOp::ColorHsi,
            "saturation_hsi" => CompositeOp::SaturationHsi,
            "inc_saturation_hsi" => CompositeOp::IncSaturationHsi,
            "dec_saturation_hsi" => CompositeOp::DecSaturationHsi,
            "intensity" => CompositeOp::Intensity,
            "inc_intensity" => CompositeOp::IncIntensity,
            "dec_intensity" => CompositeOp::DecIntensity,
            "copy" => CompositeOp::Copy,
            "copy_red" => CompositeOp::CopyRed,
            "copy_green" => CompositeOp::CopyGreen,
            "copy_blue" => CompositeOp::CopyBlue,
            "tangent_normalmap" => CompositeOp::TangentNormalmap,
            "colorize" => CompositeOp::Colorize,
            "bumpmap" => CompositeOp::Bumpmap,
            "combine_normal" => CompositeOp::CombineNormal,
            "clear" => CompositeOp::Clear,
            "dissolve" => CompositeOp::Dissolve,
            "displace" => CompositeOp::Displace,
            "nocomposition" => CompositeOp::Nocomposition,
            "pass through" => CompositeOp::PassThrough,
            "darker color" => CompositeOp::DarkerColor,
            "lighter color" => CompositeOp::LighterColor,
            "undefined" => CompositeOp::Undefined,
            "reflect" => CompositeOp::Reflect,
            "glow" => CompositeOp::Glow,
            "freeze" => CompositeOp::Freeze,
            "heat" => CompositeOp::Heat,
            "glow_heat" => CompositeOp::GlowHeat,
            "heat_glow" => CompositeOp::HeatGlow,
            "reflect_freeze" => CompositeOp::ReflectFreeze,
            "freeze_reflect" => CompositeOp::FreezeReflect,
            "heat_glow_freeze_reflect_hybrid" => CompositeOp::HeatGlowFreezeReflectHybrid,
            "lambert_lighting" => CompositeOp::LambertLighting,
            "lambert_lighting_gamma2.2" => CompositeOp::LambertLightingGamma22,
            _ => return Err(UnknownCompositeOp(s.to_owned())),
        })
    }
}
